name: Build and Test

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
    unit-test:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - name: Checkout submodules
            run : git submodule update --init --recursive
          - name: Run unit test
            run: ./unit-test.sh
    full-test:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - name: Checkout submodules
            run : git submodule update --init --recursive
          - name: Run full test
            run: ./full-test.sh
