name: Build and Test

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
    unit-test:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - name: Checkout submodules
          - name: Run unit test
            run: ./unit-test.sh
    full-test:
        container: cuaesd/aesd-autotest:24-assignment3
        runs-on: self-hosted
        steps:
          - uses: actions/checkout@v2
          - name: Checkout submodules
          - name: Run full test
            run: ./full-test.sh
